# -- Site Configuration --

theme = "congo"

baseURL = "https://istvnurbn.me/"
defaultContentLanguage = "en"

enableRobotsTXT = true

[pagination]
pagerSize = 7

summaryLength = 0

[permalinks]
[permalinks.page]
posts = '/:year/:month/:title/'

[outputs]
home = ["HTML", "RSS", "JSON"]
