# -- Main Menu --

[[main]]
name = "posts"
pageRef = "posts"
weight = 10

[[main]]
name = "tags"
pageRef = "tags"
weight = 20

[[main]]
name = "about"
pageRef = "about"
weight = 30

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

# [[footer]]
# name = "tags"
# pageRef = "tags"
# weight = 10
