# -- Theme Options --

colorScheme = "ocean"
defaultThemeColor = "#FFFFFF"
defaultAppearance = "light"
autoSwitchAppearance = false

enableSearch = false
enableCodeCopy = true
enableImageLazyLoading = true
enableImageWebp = true
enableQuicklink = true

fingerprintAlgorithm = "sha256"

[header]
layout = "hybrid"
logo = "img/logo.png"
# logoDark = "img/dark-logo.jpg"
showTitle = true

[footer]
showCopyright = true
showThemeAttribution = false
showAppearanceSwitcher = false
showScrollToTop = true

[homepage]
layout = "profile"
showRecent = false
recentLimit = 5

[article]
showDate = true
showDateUpdated = true
showAuthor = false
showBreadcrumbs = true
showDraftLabel = false
showEdit = true
editURL = "https://github.com/istvnurbn/istvnurbn.github.io/blob/main/content/"
editAppendPath = true
showHeadingAnchors = false
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = false
showTaxonomies = false
showWordCount = false
showComments = false

[list]
showBreadcrumbs = true
showSummary = true
showTableOfContents = false
showTaxonomies = false
groupByYear = true
paginationWidth = 1

[sitemap]
excludedKinds = ["taxonomy", "term"]

[taxonomy]
showTermCount = true
